name: Publish new version to NPM

env:
    node_version: 20.x
    package_manager: yarn # or npm
    install_command: yarn install # or npm ci
    script_command: yarn # or npm run
    NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    NODE_REGISTRY: 'https://registry.npmjs.org' # setup credentials
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # pass token to generate sync release via changelogen

on:
    workflow_dispatch: # manual trigger

permissions:
    contents: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.node_version }}
                  cache: ${{ env.package_manager }}
                  registry-url: ${{ env.NODE_REGISTRY }}

            - name: Install dependencies
              run: ${{ env.install_command }}

            - name: Run TypeCheck
              run: |
                  ${{ env.script_command }} nuxi prepare

            - name: Build package
              run: ${{ env.script_command }} prepack

            - name: Generate changelog and publish package
              run: |
                  git config --global user.name "changelog_action"
                  git config --global user.email "minhcanhdn0704@gmail.com"
                  ${{ env.script_command }} changelogen --release --push --publish
